language: go

go:
  - 1.6
  - tip

sudo: false

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
